language: cpp
compiler: gcc
sudo: required
os: linux
dist: jammy
install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install -yq build-essential gcc-12 g++-12 make bison flex libpthread-stubs0-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 40 --slave /usr/bin/g++ g++ /usr/bin/g++-12
  - echo 2 | sudo update-alternatives --config gcc
  - |
    CMAKE_URL="https://cmake.org/files/LatestRelease/cmake-3.24.1-linux-x86_64.tar.gz"
    mkdir ${TRAVIS_BUILD_DIR}/cmake-local && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${TRAVIS_BUILD_DIR}/cmake-local
    export PATH=${TRAVIS_BUILD_DIR}/cmake-local/bin:${PATH}
after_install:
  - g++ --version
script:
  - cmake -G 'Unix Makefiles'
  - make -j2
  - ./pbrt_test
